### ISSUE TITLE
regions v0.6 issues

### ISSUE THREAD

**Issue by bwgref** [NuSTAR/nustar-gen-utils#93]
Seems to be some issues using regions 0.6 with some meta data when doing the region checking.

**Comment by bwgref** [comment]
For now, forcing regions==0.5 in requirements.txt until I figure out what changed in the metadata. #94

**Comment by mgullik** [comment]
Hi Brian, 
I also faced a problem with the new version of the region package. I noticed that the metadata 'include' returns 1 and not True.  
I tried implementing a solution that doesn't break the code for regions version 0.5 

for ri in reg:
        assert ri.meta['include'] == 1 or ri.meta['include'] is True, \
            f'\n {regfile} has an exclusion region first! \n Put the source region first instead!'
        break

If it works I can create a PR, but since it is one line of code you can also change it directly. 
Let me know what you think. 

Gullo

**Comment by bwgref** [comment]
@mgullik I think there are more API changes in regions that were causing problems...have you made these local changes and made sure it all works?

**Comment by bwgref** [comment]
Closed in #112

**Comment by mgullik** [comment]
Hi @bwgref, 

sorry I couldn't answer before. 
I saw you changed the assert to check the region. I think it should work now.
